# Generated by Django 3.2.7 on 2021-10-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincome',
            old_name='amount_spent',
            new_name='amount_earned',
        ),
    ]
